version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - payment-net
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - payment-net

networks:
  payment-net:
    driver: bridge
